# Generated by Django 6.0.3 on 2026-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carboncredit',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
