# Generated by Django 6.0.3 on 2026-03-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carboncredit_blockchain_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
    ]
