# Generated by Django 6.0.3 on 2026-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certificate_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
