# Generated by Django 6.0.3 on 2026-03-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_created_at_creditrequest_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_farmer', to='api.user'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='government_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.project'),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='request_type',
            field=models.CharField(choices=[('FARMER_REQUEST', 'Farmer Request'), ('BULK_POOL_REQUEST', 'Bulk Pool Request')], default='BULK_POOL_REQUEST', max_length=50),
        ),
    ]
