# Generated by Django 6.0.3 on 2026-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_creditrequest_farmer_creditrequest_government_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='credit_request_rejection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='credit_request_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_rejection_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='rejection_evidence',
            field=models.FileField(blank=True, null=True, upload_to='rejections/'),
        ),
    ]
